# Generated by Django 5.1.5 on 2025-01-18 13:43

import django.db.models.deletion
import django_ckeditor_5.fields
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxz123456789', editable=False, length=22, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('governor', models.CharField(max_length=250)),
                ('about', django_ckeditor_5.fields.CKEditor5Field(default='<p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at ligula purus. Praesent aliquet ipsum risus, nec interdum nunc tempus quis. Proin ultricies mauris urna, vel sagittis libero fermentum in. Sed eleifend varius nisl eu ullamcorper. Vestibulum condimentum cursus pretium. Aenean sed nibh ac dui pulvinar porttitor ut id neque. Sed consequat sapien sed magna venenatis lacinia. Praesent ullamcorper dignissim viverra. Curabitur ac odio et ante volutpat condimentum. Pellentesque eu faucibus ipsum. Sed est ante, accumsan id tortor vitae, vestibulum auctor magna. Vivamus in neque neque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam non leo sit amet nunc maximus bibendum vitae fringilla ex. </p>')),
                ('area_km_kv', models.DecimalField(decimal_places=2, default=45.58, max_digits=10)),
                ('people', models.PositiveIntegerField(default=25000)),
                ('total_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Tuman byudjeti')),
                ('poverty_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Qashshoqlik darajasi (%)')),
                ('literacy_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Savodxonlik darajasi (%)')),
                ('unemployment_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Ishsizlik darajasi (%)')),
                ('healthcare_facilities', models.PositiveIntegerField(default=0, verbose_name='Tibbiyot muassasalari soni')),
                ('educational_institutions', models.PositiveIntegerField(default=0, verbose_name="Ta'lim muassasalari soni")),
                ('industrial_units', models.PositiveIntegerField(default=0, verbose_name='Sanoat korxonalari soni')),
                ('average_income_per_person', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name="Aholi boshiga o'rtacha daromad")),
                ('birth_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name="Tug'ilish ko'rsatkichi")),
                ('death_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name="O'lim ko'rsatkichi")),
                ('change_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uuid'],
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxz123456789', editable=False, length=22, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('house_boss', models.CharField(max_length=200)),
                ('house_number', models.PositiveIntegerField()),
                ('a_b', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=200)),
                ('status', models.CharField(choices=[('POORER', 'POORER'), ('MIDDLE', 'MIDDLE'), ('RICH', 'RICH')], max_length=200)),
                ('people', models.PositiveIntegerField(blank=True, default=5)),
                ('area_kv_m', models.DecimalField(decimal_places=2, default=415.5, max_digits=15)),
                ('education_high', models.PositiveIntegerField(default=0, verbose_name="Oliy ta'lim olganlar")),
                ('education_middle', models.PositiveIntegerField(default=0, verbose_name="O'rta ta'lim olganlar")),
                ('no_education', models.PositiveIntegerField(default=0, verbose_name="Ta'lim olmaganlar")),
                ('electricity_available', models.BooleanField(default=False, verbose_name='Elektr energiyasi mavjudligi')),
                ('water_available', models.BooleanField(default=False, verbose_name="Suv ta'minoti mavjudligi")),
                ('gas_available', models.BooleanField(default=False, verbose_name="Gaz ta'minoti mavjudligi")),
            ],
            options={
                'ordering': ['house_number', 'a_b'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxz123456789', editable=False, length=22, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('governor', models.CharField(max_length=250)),
                ('about', django_ckeditor_5.fields.CKEditor5Field(default='<p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at ligula purus. Praesent aliquet ipsum risus, nec interdum nunc tempus quis. Proin ultricies mauris urna, vel sagittis libero fermentum in. Sed eleifend varius nisl eu ullamcorper. Vestibulum condimentum cursus pretium. Aenean sed nibh ac dui pulvinar porttitor ut id neque. Sed consequat sapien sed magna venenatis lacinia. Praesent ullamcorper dignissim viverra. Curabitur ac odio et ante volutpat condimentum. Pellentesque eu faucibus ipsum. Sed est ante, accumsan id tortor vitae, vestibulum auctor magna. Vivamus in neque neque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam non leo sit amet nunc maximus bibendum vitae fringilla ex. </p>')),
                ('total_area_km2', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('population_density', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='aholi zichligi')),
                ('people', models.PositiveIntegerField(default=2500000)),
                ('gdp', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='yalpi ichki mahsulot')),
                ('unemployment_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='ishga joylashish darajasi')),
                ('literacy_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='savodxonlik darajasi')),
                ('median_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name="o'rtacha daromad")),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uuid'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxz123456789', editable=False, length=22, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('continent', models.CharField(choices=[('Afrika', 'Afrika'), ('Amerika', 'Amerika'), ('Asia', 'Asia'), ('Europa', 'Europa'), ('Oceania', 'Oceania')], max_length=200, null=True)),
                ('title', models.CharField(max_length=200)),
                ('president', models.CharField(max_length=250)),
                ('about', django_ckeditor_5.fields.CKEditor5Field(default='<p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at ligula purus. Praesent aliquet ipsum risus, nec interdum nunc tempus quis. Proin ultricies mauris urna, vel sagittis libero fermentum in. Sed eleifend varius nisl eu ullamcorper. Vestibulum condimentum cursus pretium. Aenean sed nibh ac dui pulvinar porttitor ut id neque. Sed consequat sapien sed magna venenatis lacinia. Praesent ullamcorper dignissim viverra. Curabitur ac odio et ante volutpat condimentum. Pellentesque eu faucibus ipsum. Sed est ante, accumsan id tortor vitae, vestibulum auctor magna. Vivamus in neque neque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam non leo sit amet nunc maximus bibendum vitae fringilla ex. </p>')),
                ('flag', models.ImageField(blank=True, upload_to='')),
                ('anthem', models.TextField(default='<p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at ligula purus. Praesent aliquet ipsum risus, nec interdum nunc tempus quis. Proin ultricies mauris urna, vel sagittis libero fermentum in. Sed eleifend varius nisl eu ullamcorper. Vestibulum condimentum cursus pretium. Aenean sed nibh ac dui pulvinar porttitor ut id neque. Sed consequat sapien sed magna venenatis lacinia. Praesent ullamcorper dignissim viverra. Curabitur ac odio et ante volutpat condimentum. Pellentesque eu faucibus ipsum. Sed est ante, accumsan id tortor vitae, vestibulum auctor magna. Vivamus in neque neque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam non leo sit amet nunc maximus bibendum vitae fringilla ex. </p>')),
                ('emblem', models.ImageField(blank=True, upload_to='')),
                ('language', models.CharField(max_length=200)),
                ('area_km_kv', models.DecimalField(decimal_places=2, default=450.54, max_digits=10)),
                ('people', models.PositiveIntegerField(default=40000000)),
                ('capital', models.CharField(default='Option', max_length=200)),
                ('gdp', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Umumiy ichki mahsulot (GDP)')),
                ('unemployment_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name=' Ishsizlik darajasi')),
                ('inflation_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Inflyatsiya darajasi')),
                ('poverty_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Qashshoqlik darajasi')),
                ('literacy_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Savodxonlik darajasi')),
                ('life_expectancy', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Hayot davomiyligi')),
                ('population_growth_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name="Aholi o'sish darajasi")),
                ('urban_population_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Shahar aholisi foizi')),
                ('birth_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name="Tug'ilish darajasi")),
                ('death_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name="O'lim darajasi")),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uuid'],
            },
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxz123456789', editable=False, length=22, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(default='example@mail.ru', max_length=254)),
                ('BIO', django_ckeditor_5.fields.CKEditor5Field(default='<p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque at ligula purus. Praesent aliquet ipsum risus, nec interdum nunc tempus quis. Proin ultricies mauris urna, vel sagittis libero fermentum in. Sed eleifend varius nisl eu ullamcorper. Vestibulum condimentum cursus pretium. Aenean sed nibh ac dui pulvinar porttitor ut id neque. Sed consequat sapien sed magna venenatis lacinia. Praesent ullamcorper dignissim viverra. Curabitur ac odio et ante volutpat condimentum. Pellentesque eu faucibus ipsum. Sed est ante, accumsan id tortor vitae, vestibulum auctor magna. Vivamus in neque neque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam non leo sit amet nunc maximus bibendum vitae fringilla ex. </p>')),
                ('status', models.CharField(choices=[('Kindergarten', 'Kindergarten'), ('Schoolboy', 'Schoolboy'), ('Student', 'Student'), ('Worker', 'Worker')], max_length=200)),
                ('information', models.CharField(choices=[('HIGH', 'High'), ('MIDDLE', 'Middle'), ('NO', 'No')], default='NO', max_length=200)),
                ('education_level', models.CharField(default='Middle', max_length=100, verbose_name="Ta'lim darajasi")),
                ('working_hours_per_week', models.PositiveIntegerField(default=0, verbose_name='Haftalik ish soatlari')),
                ('gender_distribution', models.CharField(choices=[('MALE', 'MALE'), ('FAMALE', 'FAMALE'), ('OTHER', 'OTHER')], max_length=50, verbose_name='Jins')),
                ('living_space_per_person', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name="Uyda har bir a'zoga to'g'ri keladigan maydon (m²)")),
                ('house', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='human', to='main.house')),
            ],
            options={
                'ordering': ['-uuid'],
            },
        ),
        migrations.CreateModel(
            name='MFY',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxz123456789', editable=False, length=22, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('chairman', models.CharField(max_length=250)),
                ('area_km_kv', models.DecimalField(decimal_places=2, default=15.75, max_digits=10)),
                ('people', models.PositiveIntegerField(default=8500)),
                ('total_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='MFY byudjeti')),
                ('poverty_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Qashshoqlik darajasi (%)')),
                ('literacy_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Savodxonlik darajasi (%)')),
                ('unemployment_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Ishsizlik darajasi (%)')),
                ('healthcare_facilities', models.PositiveIntegerField(default=0, verbose_name='Tibbiyot muassasalari soni')),
                ('educational_institutions', models.PositiveIntegerField(default=0, verbose_name="Ta'lim muassasalari soni")),
                ('industrial_units', models.PositiveIntegerField(default=0, verbose_name='Sanoat korxonalari soni')),
                ('average_income_per_person', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name="Aholi boshiga o'rtacha daromad")),
                ('birth_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name="Tug'ilish ko'rsatkichi")),
                ('death_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name="O'lim ko'rsatkichi")),
                ('change_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MFY', to='main.district')),
            ],
            options={
                'ordering': ['-uuid'],
            },
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxz123456789', editable=False, length=22, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('elder', models.CharField(default='Jhon Doe', max_length=250)),
                ('area_km_kv', models.DecimalField(decimal_places=2, default=4.65, max_digits=15)),
                ('houses', models.PositiveIntegerField(default=85)),
                ('people', models.PositiveIntegerField(default=530)),
                ('population_density', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Aholi zichligi (kishi/km²)')),
                ('unemployment_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Ishsizlik darajasi (%)')),
                ('avg_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name="O'rtacha daromad (so'm)")),
                ('young_population', models.PositiveIntegerField(default=0, verbose_name='Kichik yoshdagi aholi (0-14)')),
                ('working_population', models.PositiveIntegerField(default=0, verbose_name='Ishchi yoshdagi aholi (15-64)')),
                ('elderly_population', models.PositiveIntegerField(default=0, verbose_name='Keksaygan yoshdagi aholi (65+)')),
                ('education_high', models.PositiveIntegerField(default=0, verbose_name="Oliy ta'lim olganlar")),
                ('education_middle', models.PositiveIntegerField(default=0, verbose_name="O'rta ta'lim olganlar")),
                ('no_education', models.PositiveIntegerField(default=0, verbose_name="Ta'lim olmaganlar")),
                ('good_houses', models.PositiveIntegerField(default=0, verbose_name='Yaxshi sharoitdagi uylar')),
                ('average_houses', models.PositiveIntegerField(default=0, verbose_name="O'rta sharoitdagi uylar")),
                ('poor_houses', models.PositiveIntegerField(default=0, verbose_name='Yomon sharoitdagi uylar')),
                ('MFY', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.mfy')),
            ],
            options={
                'ordering': ['-uuid'],
            },
        ),
        migrations.AddField(
            model_name='house',
            name='neighborhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house', to='main.neighborhood'),
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district', to='main.region'),
        ),
        migrations.AddField(
            model_name='region',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region', to='main.state'),
        ),
    ]
