# Generated by Django 5.1.5 on 2025-01-18 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mfy_about_alter_state_emblem_alter_state_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='MFY',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='neighborhood', to='main.mfy'),
        ),
    ]
