# Generated by Django 5.1.5 on 2025-01-18 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_neighborhood_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='houses',
        ),
    ]
