# Generated by Django 5.1.5 on 2025-01-18 16:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_neighborhood_houses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='average_houses',
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='good_houses',
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='poor_houses',
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='change_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
