# Generated by Django 5.1.5 on 2025-01-18 17:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_house_change_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='change_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
