# Generated by Django 5.1.5 on 2025-01-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_human_education_level_human_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='gender_distribution',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FAMALE', 'FAMALE')], max_length=50, verbose_name='Jins'),
        ),
    ]
